baseURL = "https://romantic-kalam-0cd29f.netlify.app/"
languageCode = "en-us"
title = "LoveEnglishMoscow"
theme = "hugo-scroll"
[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© LoveEnglishMoscow"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "English School"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"
