backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images"
pubilc_folder: "/images"

publish_mode: editorial_workflow

site_url: https://loveengmoscow.netlify.app/

collections:
  - label: "Product"
    name: product
    identifier_field: name
    folder: "content/product"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}

  - label: "Homepage"
    name: homepage
    identifier_field: title
    folder: "content/homepage"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
